# Generated by Django 4.0.4 on 2022-06-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_worker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='Role',
            field=models.CharField(default='worker_role', max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(default='', upload_to='images/', verbose_name='photo'),
        ),
    ]
